name: PHP Lint and Code Style Check

on:
  pull_request:
    branches:
      - main

jobs:
  php-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # Укажите вашу версию PHP

      - name: Validate PHP syntax
        run: find . -name "*.php" -not -path "./vendor/*" -exec php -l {} \;

      - name: Install PHP_CodeSniffer
        run: composer global require "squizlabs/php_codesniffer=*"

      - name: Install dependencies
        run: composer install

      - name: Check code style
        run: ~/.composer/vendor/bin/phpcs --standard=PSR12 --ignore=vendor/* .

